name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels: ["feat", "feature", "enhancement"]
  - title: "🐞 Bug Fixes"
    labels: ["fix", "bugfix", "bug"]
  - title: "🧰 Maintenance"
    labels: ["chore", "refactor", "deps", "dependencies"]
  - title: "📝 Documentation"
    labels: ["docs", "documentation"]
  - title: "⚡ Performance"
    labels: ["perf", "performance"]
  - title: "✅ Tests"
    labels: ["test", "tests"]

change-template: "- $TITLE (#$NUMBER) @$AUTHOR"

change-title-escapes: '\<*_&'

template: |
  ## What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

version-resolver:
  major:
    labels: ["breaking", "semver:major"]
  minor:
    labels: ["feat", "feature", "enhancement", "semver:minor"]
  patch:
    labels: ["fix", "bugfix", "bug", "chore", "docs", "perf", "refactor", "test", "semver:patch"]
  default: patch

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
      - "docs/**"
      - "LICENSE*"
  - label: "bug"
    branch:
      - '/^fix\/.+/'
    title:
      - "/^fix:/i"
  - label: "enhancement"
    branch:
      - '/^feat\/.+/'
      - '/^feature\/.+/'
    title:
      - "/^feat:/i"
  - label: "chore"
    title:
      - "/^chore:/i"
  - label: "refactor"
    title:
      - "/^refactor:/i"
  - label: "test"
    files:
      - "**/*.test.ts"
      - "**/*.spec.ts"
    title:
      - "/^test:/i"
  - label: "dependencies"
    files:
      - "package.json"
      - "pnpm-lock.yaml"
      - "**/package.json"

exclude-labels:
  - "skip-changelog"
  - "no-changelog"

exclude-contributors:
  - "dependabot"
