name = "hatago-workers-example"
main = "src/index.ts"
compatibility_date = "2024-12-26"

# KV Namespaces for configuration storage
[[kv_namespaces]]
binding = "CONFIG_KV"
id = "your-config-kv-id"
preview_id = "your-config-kv-preview-id"

# Durable Objects for session management
[[durable_objects.bindings]]
name = "SESSION_DO"
class_name = "SessionDurableObject"
script_name = "hatago-workers-example"

# Optional: Analytics Engine for metrics
# [[analytics_engine_datasets]]
# binding = "METRICS"