blank_issues_enabled: false
contact_links:
  - name: Security issues (private via X DM)
    url: https://x.com/_himorishige
    about: Please report security vulnerabilities via X (Twitter) DM to @_himorishige.
  - name: GitHub Security Advisories
    url: https://github.com/himorishige/hatago-mcp-hub/security/advisories
    about: Prefer private advisories when possible to coordinate fixes.
