name: PR Tests (hub + transport)

on:
  pull_request:
  merge_group:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: true

      - name: Build core deps for tests (core, runtime)
        run: |
          pnpm -w -F @himorishige/hatago-core -F @himorishige/hatago-runtime build

      - name: Run tests (hub, transport)
        run: |
          pnpm -r --filter @himorishige/hatago-hub --filter @himorishige/hatago-transport run test
